### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by Ilikepieitsgood** [BlueThecno/Mindustry-Diamond-Mod#1]
It has content errors

**Comment by BlueTechnoCat** [comment]
Can you tell me the exact problem that you are having, just saying "has errors" doesn't help

**Comment by Ilikepieitsgood** [comment]
Here
![Screenshot_20210216-181952_Mindustry](https://user-images.githubusercontent.com/78336842/108138471-a79c5800-7083-11eb-8f8c-5c24c88f7b43.jpg)

**Comment by BlueTechnoCat** [comment]
Should be fixed now

EDIT: Just checked on the game, It's works now.
