### ISSUE TITLE
TechTree

### ISSUE THREAD

**Issue by NeonAurora** [BlueThecno/Mindustry-Diamond-Mod#4]
Sorry to trouble u like this. But i cant seem to find any units for the diamond air factory in the diamond mod. Would u be pls kind enough to notify what i am doing wrong or is it not included in the mod? actually i liked the mod so it will be really a pleasure if u can tell me what i am doing wrong here
![UNITS](https://user-images.githubusercontent.com/106610057/177485584-bc11ea05-fd30-44bb-b73e-b261351aa6ce.jpg)
![CONTENT](https://user-images.githubusercontent.com/106610057/177485605-c78658f1-3197-4e1a-9fd6-153e8bd73d94.JPG)
.

the diamond air factory doesnt have any thing to produce here. where can i unlock them?

**Comment by BlueTechnoCat** [comment]
What version of the game are you using? and the first units are unlocked after tier 3 normal units (antumbra and such)
